---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r read}
library(dplyr)
setwd("~/Desktop/Reproducible research/Assign_1")
data<-read.table("activity.csv", header = TRUE, sep = ",")
days <- group_by(data, date)
intervals <- group_by(data, interval)
total_by_day <- summarize(days, s1 = sum(steps, na.rm = TRUE))
avg_by_interval <- summarize(intervals, avg = mean(steps, na.rm = TRUE))
```


## What is mean total number of steps taken per day?

### Histogram

```{r histogram}
barplot(total_by_day$s1, main = "Number of steps by days", ylab = "Number of steps")
mean(total_by_day$s1)
median(total_by_day$s1)


```

### Mean and median
```{r mean}
mean(total_by_day$s1)
median(total_by_day$s1)
```

### Time series plots

```{r time series}

plot(avg ~ interval, avg_by_interval, type = "l")
```

## What is the average daily activity pattern?

### interval with the max avg of steps

```{r max}
which(avg_by_interval$avg == max(avg_by_interval$avg))
```

## Imputing missing values

```{r missing}
sum(is.na(data$steps))
```

## Are there differences in activity patterns between weekdays and weekends?
